GET http://localhost:3000/products

###
GET http://localhost:3000/products/1

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product 2",
    "price": 100
}

###
PATCH  http://localhost:3000/products/1
Content-Type: application/json

{
    "name": "Product 1 changed",
    "price": 150
}

###
DELETE http://localhost:3000/products/5
