###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/1

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product 2",
    "price": 100
}

###
PATCH  http://localhost:3000/products/6
Content-Type: application/json

{
    "name": "Playstation 5",
    "price": 3500
}

###
DELETE http://localhost:3000/products/5


------------------

###
POST http://localhost:3000/stock-inputs
Content-Type: application/json

{
    "quantity": 100,
    "product_id": 6,
    "date": "2021-01-01"
}